parse-server:
  image: yongjhih/parse-server
  ports:
    - "1337:1337"
  environment:
    PORT: 1337
    DATABASE_URI: $DATABASE_URI
    APP_ID: $APP_ID
    MASTER_KEY: $MASTER_KEY
    PARSE_MOUNT: $PARSE_MOUNT # /parse
    COLLECTION_PREFIX: $COLLECTION_PREFIX
    CLIENT_KEY: $CLIENT_KEY
    REST_API_KEY: $REST_API_KEY
    DOTNET_KEY: $DOTNET_KEY
    JAVASCRIPT_KEY: $JAVASCRIPT_KEY
    FILE_KEY: $FILE_KEY
    FACEBOOK_APP_IDS: $FACEBOOK_APP_IDS
    SERVER_URL: $SERVER_URL
    MAX_UPLOAD_SIZE: $MAX_UPLOAD_SIZE
    GCM_ID: $GCM_ID
    GCM_KEY: $GCM_KEY
    PRODUCTION_PFX: $PRODUCTION_PFX
    PRODUCTION_PASSPHRASE: $PRODUCTION_PASSPHRASE
    PRODUCTION_BUNDLE_ID: $PRODUCTION_BUNDLE_ID
    PRODUCTION_CERT: $PRODUCTION_CERT
    PRODUCTION_KEY: $PRODUCTION_KEY
    DEV_PFX: $DEV_PFX
    DEV_PASSPHRASE: $DEV_PASSPHRASE
    DEV_BUNDLE_ID: $DEV_BUNDLE_ID
    DEV_CERT: $DEV_CERT
    DEV_KEY: $DEV_KEY
    VERIFY_USER_EMAILS: $VERIFY_USER_EMAILS
    EMAIL_MODULE: $EMAIL_MODULE
    EMAIL_FROM: $EMAIL_FROM
    EMAIL_DOMAIN: $EMAIL_DOMAIN
    EMAIL_API_KEY: $EMAIL_API_KEY
    EMAIL_DISPLAY_NAME: $EMAIL_DISPLAY_NAME
    EMAIL_REPLY_TO: $EMAIL_REPLY_TO
    EMAIL_VERIFICATION_SUBJECT: $EMAIL_VERIFICATION_SUBJECT
    EMAIL_VERIFICATION_BODY: $EMAIL_VERIFICATION_BODY
    EMAIL_PASSWORD_RESET_SUBJECT: $EMAIL_PASSWORD_RESET_SUBJECT
    EMAIL_PASSWORD_RESET_BODY: $EMAIL_PASSWORD_RESET_BODY
    ENABLE_ANON_USERS: $ENABLE_ANON_USERS # 1
    ALLOW_CLIENT_CLASS_CREATION: $ALLOW_CLIENT_CLASS_CREATION # 1
    PARSE_EXPERIMENTAL_CONFIG_ENABLED: $PARSE_EXPERIMENTAL_CONFIG_ENABLED # 0
    TESTING: $TESTING # 0
    APP_NAME: $APP_NAME
    PUBLIC_SERVER_URL: $PUBLIC_SERVER_URL
    TRUST_PROXY: $TRUST_PROXY
    S3_ACCESS_KEY:    $S3_ACCESS_KEY
    S3_SECRET_KEY:    $S3_SECRET_KEY
    S3_BUCKET:        $S3_BUCKET
    S3_DIRECT:        $S3_DIRECT
    GCP_PROJECT_ID:   $GCP_PROJECT_ID
    GCP_KEYFILE_PATH: $GCP_KEYFILE_PATH
    GCS_BUCKET:       $GCS_BUCKET
    GCS_DIRECT:       $GCS_DIRECT
    AZURE_ACCOUNT:    $AZURE_ACCOUNT
    AZURE_CONTAINER:  $AZURE_CONTAINER
    AZURE_ACCESS_KEY: $AZURE_ACCESS_KEY
    AZURE_DIRECT:     $AZURE_DIRECT
    LIVEQUERY_SUPPORT: $LIVEQUERY_SUPPORT
    LIVEQUERY_CLASSES: $LIVEQUERY_CLASSES
    GRAPHQL_SUPPORT:  $GRAPHQL_SUPPORT
    GRAPHQL_SCHEMA:   $GRAPHQL_SCHEMA
    LOG_LEVEL:        $LOG_LEVEL
  links:
    - mongo
  volumes_from:
    - parse-cloud-code
  volumes:
    - /parse/cloud
    - "./volumes/certs:/certs"

parse-cloud-code:
  image: yongjhih/parse-cloud-code
  volumes:
    - /parse/cloud
  command: "ls /parse/cloud"

git:
  image: yongjhih/parse-server:git
  ports:
    - "2022:22"
  environment:
    PORT: 22
  volumes_from:
    - parse-server

mongo:
  image: mongo:3.0.8
  ports:
    - "27018:27017"
  volumes_from:
    - mongo-data


mongo-data:
  image: mongo
  volumes:
    - /data/db
  command: "--break-mongo"

parse-dashboard:
  image: yongjhih/parse-dashboard:1.0.18
  links:
    - parse-server
  environment:
    APP_ID: $APP_ID
    MASTER_KEY: $MASTER_KEY
    APP_NAME: $APP_NAME
    ALLOW_INSECURE_HTTP: $PARSE_DASHBOARD_ALLOW_INSECURE_HTTP
    USER1: $USER1
    USER1_PASSWORD: $USER1_PASSWORD
    PARSE_DASHBOARD_ALLOW_INSECURE_HTTP: $PARSE_DASHBOARD_ALLOW_INSECURE_HTTP
    SERVER_URL: $SERVER_URL
    PARSE_DASHBOARD_SERVER_URL: $SERVER_URL
    PARSE_DASHBOARD_MASTER_KEY: $MASTER_KEY
    PARSE_DASHBOARD_APP_ID: $APP_ID
    PARSE_DASHBOARD_APP_NAME: $APP_NAME
    PARSE_DASHBOARD_USER_ID: $PARSE_DASHBOARD_USER_ID
    PARSE_DASHBOARD_USER_PASSWORD: $PARSE_DASHBOARD_USER_PASSWORD
    PARSE_DASHBOARD_CONFIG: $PARSE_DASHBOARD_CONFIG
    MOUNT_PATH: $PARSE_DASHBOARD_MOUNT_PATH
    TRUST_PROXY: $PARSE_DASHBOARD_TRUST_PROXY
    PORT: 4040
  ports:
    - "4040:4040"
